[build]
  command = "cd src/vanilla && yarn install && yarn build"
  publish = "src/vanilla/dist"
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[template.environment]
  LIFF_ID = "Your LIFF ID which is aquired from LINE Dev Center"

